### ISSUE TITLE
Dataset not found?

### ISSUE THREAD

**Issue by Clapboiz** [ArielCyber/Cisco_Ariel_Uni_API_security_challenge#1]
Hello sir,

The dataset to this repo was unavailable, can you update it. 
This is my gmail: Phamconglap03@gmail.com (for further contact)

Thank you so much.

**Comment by udi-aharon** [comment]
@Clapboiz fixed

**Comment by udi-aharon** [comment]
Resolved

**Comment by Clapboiz** [comment]
Thank you so much.
